
L€È¯ %BScripts/Fields/include_chara_talk_ch0000_00_red_present_item_1.luad
NÀÌì %DScripts/Fields/include_chara_talk_ch0001_00_kukui_present_item_1.luad
O€Ñ©¡%EScripts/Fields/include_chara_talk_ch0002_00_kotone_present_item_1.luad
NÀÕæ¡%DScripts/Fields/include_chara_talk_ch0003_00_calme_present_item_1.luad
M€Ú£¢%CScripts/Fields/include_chara_talk_ch0004_00_toko_present_item_1.luad
NÀŞà¢%DScripts/Fields/include_chara_talk_ch0005_00_kanna_present_item_1.luad
L€ã£%BScripts/Fields/include_chara_talk_ch0006_00_oba_present_item_1.luad
PÀçÚ£%FScripts/Fields/include_chara_talk_ch0007_00_acerola_present_item_1.luad
N€ì—¤%DScripts/Fields/include_chara_talk_ch0008_00_erika_present_item_1.luad
NÀğÔ¤%DScripts/Fields/include_chara_talk_ch0009_00_senri_present_item_1.luad
P€õ‘¥%FScripts/Fields/include_chara_talk_ch0010_00_maximum_present_item_1.luad
OÀùÎ¥%EScripts/Fields/include_chara_talk_ch0011_00_homika_present_item_1.luad
N€ş‹¦%DScripts/Fields/include_chara_talk_ch0012_00_corni_present_item_1.luad
MÀ‚É¦%CScripts/Fields/include_chara_talk_ch0013_00_hapu_present_item_1.luad
OÕ†§%EScripts/Fields/include_chara_talk_ch0014_01_cheren_present_item_1.luad
PÀ‹Ã§%FScripts/Fields/include_chara_talk_ch0015_00_takeshi_present_item_1.luad
PĞÙÃ§%FScripts/Fields/include_chara_talk_ch0015_01_takeshi_present_item_1.luad
N€€¨%DScripts/Fields/include_chara_talk_ch0016_00_huuro_present_item_1.luad
MÀ”½¨%CScripts/Fields/include_chara_talk_ch0017_00_leaf_present_item_1.luad
N€™ú¨%DScripts/Fields/include_chara_talk_ch0018_00_chris_present_item_1.luad
MÀ·©%CScripts/Fields/include_chara_talk_ch0019_00_yuki_present_item_1.luad
M€¢ô©%CScripts/Fields/include_chara_talk_ch0020_00_toya_present_item_1.luad
NÀ¦±ª%DScripts/Fields/include_chara_talk_ch0021_00_green_present_item_1.luad
M€«îª%CScripts/Fields/include_chara_talk_ch0022_00_urup_present_item_1.luad
MÀ¯««%CScripts/Fields/include_chara_talk_ch0023_00_momi_present_item_1.luad
P€´è«%FScripts/Fields/include_chara_talk_ch0024_00_shikimi_present_item_1.luad
OÀ¸¥¬%EScripts/Fields/include_chara_talk_ch0025_00_suzuna_present_item_1.luad
N€½â¬%DScripts/Fields/include_chara_talk_ch0026_00_akane_present_item_1.luad
OÀÁŸ­%EScripts/Fields/include_chara_talk_ch0027_00_natane_present_item_1.luad
N€ÆÜ­%DScripts/Fields/include_chara_talk_ch0028_00_ibuki_present_item_1.luad
NÀÊ™®%DScripts/Fields/include_chara_talk_ch0029_00_asuna_present_item_1.luad
L€ÏÖ®%BScripts/Fields/include_chara_talk_ch0030_00_ran_present_item_1.luad
LÀÓ“¯%BScripts/Fields/include_chara_talk_ch0031_00_fuu_present_item_1.luad
O€ØĞ¯%EScripts/Fields/include_chara_talk_ch0032_00_yanagi_present_item_1.luad
NÀÜ°%DScripts/Fields/include_chara_talk_ch0033_00_yakon_present_item_1.luad
R€áÊ°%HScripts/Fields/include_chara_talk_ch0034_00_matsurika_present_item_1.luad
QÀå‡±%GScripts/Fields/include_chara_talk_ch0035_00_matthies_present_item_1.luad
O€êÄ±%EScripts/Fields/include_chara_talk_ch0036_00_mamane_present_item_1.luad
OÀî²%EScripts/Fields/include_chara_talk_ch0037_00_fukuji_present_item_1.luad
O€ó¾²%EScripts/Fields/include_chara_talk_ch0038_00_hyouta_present_item_1.luad
NÀ÷û²%DScripts/Fields/include_chara_talk_ch0039_00_viola_present_item_1.luad
P€ü¸³%FScripts/Fields/include_chara_talk_ch0040_00_hachiku_present_item_1.luad
OÀ€ö³%EScripts/Fields/include_chara_talk_ch0041_00_nejiki_present_item_1.luad
M€…³´%CScripts/Fields/include_chara_talk_ch0042_00_nagi_present_item_1.luad
MÀ‰ğ´%CScripts/Fields/include_chara_talk_ch0043_00_toki_present_item_1.luad
Q€­µ%GScripts/Fields/include_chara_talk_ch0044_00_tsutsuji_present_item_1.luad
QÀ’êµ%GScripts/Fields/include_chara_talk_ch0045_00_tsukushi_present_item_1.luad
P€—§¶%FScripts/Fields/include_chara_talk_ch0046_00_datsura_present_item_1.luad
OÀ›ä¶%EScripts/Fields/include_chara_talk_ch0047_00_itsuki_present_item_1.luad
M€ ¡·%CScripts/Fields/include_chara_talk_ch0048_00_gima_present_item_1.luad
MÀ¤Ş·%CScripts/Fields/include_chara_talk_ch0049_00_fuyo_present_item_1.luad
O€©›¸%EScripts/Fields/include_chara_talk_ch0050_00_sumomo_present_item_1.luad
OÀ­Ø¸%EScripts/Fields/include_chara_talk_ch0051_00_litchi_present_item_1.luad
O€²•¹%EScripts/Fields/include_chara_talk_ch0052_00_shizui_present_item_1.luad
OÀ¶Ò¹%EScripts/Fields/include_chara_talk_ch0053_00_zakuro_present_item_1.luad
L€»º%BScripts/Fields/include_chara_talk_ch0054_00_kyo_present_item_1.luad
NÀ¿Ìº%DScripts/Fields/include_chara_talk_ch0055_00_gampi_present_item_1.luad
S€Ä‰»%IScripts/Fields/include_chara_talk_ch0056_00_kuchinashi_present_item_1.luad
NÀÈÆ»%DScripts/Fields/include_chara_talk_ch0057_00_shiba_present_item_1.luad
O€Íƒ¼%EScripts/Fields/include_chara_talk_ch0058_00_kahiri_present_item_1.luad
PÀÑÀ¼%FScripts/Fields/include_chara_talk_ch0059_00_katsura_present_item_1.luad
M€Öı¼%CScripts/Fields/include_chara_talk_ch0060_00_anzu_present_item_1.luad
OÀÚº½%EScripts/Fields/include_chara_talk_ch0061_00_kikuko_present_item_1.luad
N€ß÷½%DScripts/Fields/include_chara_talk_ch0062_00_karin_present_item_1.luad
NÀã´¾%DScripts/Fields/include_chara_talk_ch0063_00_renbu_present_item_1.luad
N€İ¤Ë%DScripts/Fields/include_chara_talk_ch0090_00_daigo_present_item_1.luad
PÀááË%FScripts/Fields/include_chara_talk_ch0091_00_shirona_present_item_1.luad
M€æÌ%CScripts/Fields/include_chara_talk_ch0092_00_iris_present_item_1.luad
N€ï˜Í%DScripts/Fields/include_chara_talk_ch0094_00_genji_present_item_1.luad
QÀóÕÍ%GScripts/Fields/include_chara_talk_ch0095_00_cattleya_present_item_1.luad
M€ø’Î%CScripts/Fields/include_chara_talk_ch0096_00_zumi_present_item_1.luad
M …™Î%CScripts/Fields/include_chara_talk_ch0096_10_zumi_present_item_1.luad
LÀüÏÎ%BScripts/Fields/include_chara_talk_ch0097_00_mai_present_item_1.luad
L€Ï%BScripts/Fields/include_chara_talk_ch0098_00_hau_present_item_1.luad
LÀ…ÊÏ%BScripts/Fields/include_chara_talk_ch0099_00_jun_present_item_1.luad
LÀÄĞ%BScripts/Fields/include_chara_talk_ch0101_00_mei_present_item_1.luad
Là›ÊĞ%BScripts/Fields/include_chara_talk_ch0101_10_mei_present_item_1.luad
R€¥õÒ%HScripts/Fields/include_chara_talk_ch0106_00_kamitsure_present_item_1.luad
R ²ûÒ%HScripts/Fields/include_chara_talk_ch0106_10_kamitsure_present_item_1.luad
O€·éÔ%EScripts/Fields/include_chara_talk_ch0110_01_kasumi_present_item_1.luad
OÀ»¦Õ%EScripts/Fields/include_chara_talk_ch0111_00_wataru_present_item_1.luad
O€ÀãÕ%EScripts/Fields/include_chara_talk_ch0112_00_hibiki_present_item_1.luad
P€ÉİÖ%FScripts/Fields/include_chara_talk_ch0114_00_natsume_present_item_1.luad
OÀŒñİ%EScripts/Fields/include_chara_talk_ch0129_00_higana_present_item_1.luad
PÀ°Ùá%FScripts/Fields/include_chara_talk_ch0137_00_orchid1_present_item_1.luad
O€¾ã%EScripts/Fields/include_chara_talk_ch0140_00_sakaki_present_item_1.luad
PÀï¯è%FScripts/Fields/include_chara_talk_ch0151_00_melissa_present_item_1.luad
MÀø©é%CScripts/Fields/include_chara_talk_ch0153_00_prim_present_item_1.luad
NÀŠë%DScripts/Fields/include_chara_talk_ch0157_00_mache_present_item_1.luad