
)
%ACT_ON_SETTLEMENT_LAW_BRL_ANY_ANDROID
%
!ACT_ON_SETTLEMENT_LAW_BRL_ANY_IOS
)
%ACT_ON_SETTLEMENT_LAW_CAD_ANY_ANDROID
%
!ACT_ON_SETTLEMENT_LAW_CAD_ANY_IOS
(
$ACT_ON_SETTLEMENT_LAW_EUR_DE_ANDROID
$
 ACT_ON_SETTLEMENT_LAW_EUR_DE_IOS
(
$ACT_ON_SETTLEMENT_LAW_EUR_ES_ANDROID
$
 ACT_ON_SETTLEMENT_LAW_EUR_ES_IOS
(
$ACT_ON_SETTLEMENT_LAW_EUR_FR_ANDROID
$
 ACT_ON_SETTLEMENT_LAW_EUR_FR_IOS
(
$ACT_ON_SETTLEMENT_LAW_EUR_IT_ANDROID
$
 ACT_ON_SETTLEMENT_LAW_EUR_IT_IOS
)
%ACT_ON_SETTLEMENT_LAW_HKD_ANY_ANDROID

%
!ACT_ON_SETTLEMENT_LAW_HKD_ANY_IOS

(
$ACT_ON_SETTLEMENT_LAW_JPY_JP_ANDROID
$
 ACT_ON_SETTLEMENT_LAW_JPY_JP_IOS
)
%ACT_ON_SETTLEMENT_LAW_KRW_ANY_ANDROID	
%
!ACT_ON_SETTLEMENT_LAW_KRW_ANY_IOS	
)
%ACT_ON_SETTLEMENT_LAW_TWD_ANY_ANDROID

%
!ACT_ON_SETTLEMENT_LAW_TWD_ANY_IOS

(
$ACT_ON_SETTLEMENT_LAW_USD_US_ANDROID
$
 ACT_ON_SETTLEMENT_LAW_USD_US_IOS
9
5SPECIFIED_COMMERCIAL_TRANSACTIONS_LAW_BRL_ANY_ANDROID
5
1SPECIFIED_COMMERCIAL_TRANSACTIONS_LAW_BRL_ANY_IOS
9
5SPECIFIED_COMMERCIAL_TRANSACTIONS_LAW_CAD_ANY_ANDROID
5
1SPECIFIED_COMMERCIAL_TRANSACTIONS_LAW_CAD_ANY_IOS
8
4SPECIFIED_COMMERCIAL_TRANSACTIONS_LAW_EUR_DE_ANDROID
4
0SPECIFIED_COMMERCIAL_TRANSACTIONS_LAW_EUR_DE_IOS
8
4SPECIFIED_COMMERCIAL_TRANSACTIONS_LAW_EUR_ES_ANDROID
4
0SPECIFIED_COMMERCIAL_TRANSACTIONS_LAW_EUR_ES_IOS
8
4SPECIFIED_COMMERCIAL_TRANSACTIONS_LAW_EUR_FR_ANDROID
4
0SPECIFIED_COMMERCIAL_TRANSACTIONS_LAW_EUR_FR_IOS
8
4SPECIFIED_COMMERCIAL_TRANSACTIONS_LAW_EUR_IT_ANDROID
4
0SPECIFIED_COMMERCIAL_TRANSACTIONS_LAW_EUR_IT_IOS
9
5SPECIFIED_COMMERCIAL_TRANSACTIONS_LAW_HKD_ANY_ANDROID

5
1SPECIFIED_COMMERCIAL_TRANSACTIONS_LAW_HKD_ANY_IOS

8
4SPECIFIED_COMMERCIAL_TRANSACTIONS_LAW_JPY_JP_ANDROID
4
0SPECIFIED_COMMERCIAL_TRANSACTIONS_LAW_JPY_JP_IOS
9
5SPECIFIED_COMMERCIAL_TRANSACTIONS_LAW_KRW_ANY_ANDROID	
5
1SPECIFIED_COMMERCIAL_TRANSACTIONS_LAW_KRW_ANY_IOS	
9
5SPECIFIED_COMMERCIAL_TRANSACTIONS_LAW_TWD_ANY_ANDROID

5
1SPECIFIED_COMMERCIAL_TRANSACTIONS_LAW_TWD_ANY_IOS

8
4SPECIFIED_COMMERCIAL_TRANSACTIONS_LAW_USD_US_ANDROID
4
0SPECIFIED_COMMERCIAL_TRANSACTIONS_LAW_USD_US_IOS

item_exchange.buffer_timeÄı$
'
!paid_vc.max_number_of_possessionsÄÒ
#
vc.self_control_notification.1∏
#
vc.self_control_notification.2.
#
vc.self_control_notification.3êN
$
vc.self_control_notification.4∞Í
$
vc.self_control_notification.5–Ü
$
vc.self_control_notification.6¢
$
vc.self_control_notification.7êø